default: &default
  adapter: postgresql
  encoding: 'utf8'
  pool: 5
  port: 5432
  host: 'localhost'
  username: oleg
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: todo_infakt_development

test:
  <<: *default
  database: todo_infakt_test

production:
  <<: *default
  database: todo_infakt_production
